# serverless.yml

service: work-alone-apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: dist/server.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - nodemon.json
    - README.md
  excludeDevDependencies: true
plugins:
  - serverless-offline
custom:
  serverless-offline:
    noPrependStageInUrl: true
    useChildProcesses: true
